name: NestJS DevSecOps CI Pipeline

permissions:
  contents: read
  actions: read
  security-events: write
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sast:
    name: Static Analysis (Semgrep)
    runs-on: ubuntu-latest
    # 'needs' for lint and test removed as those jobs are removed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST
        run: |
          semgrep scan \
            --config auto \
            --exclude "test/*" \
            --exclude "node_modules/*" \
            --exclude "dist/*" \
            --severity ERROR \
            --sarif \
            -o semgrep_report.sarif \
            || true

      - name: Upload Semgrep SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_report.sarif

      - name: Upload SARIF to GitHub Advanced Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep_report.sarif
          category: semgrep

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [sast] # Depends on SAST completion
    outputs:
      artifact_name: nestjs-app-${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build NestJS application
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nestjs-app-${{ github.run_id }}
          path: |
            dist
            node_modules
            package.json
            yarn.lock
            # Add other files needed to run the app
  dast:
    name: Dynamic Analysis (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: build # Depends on the build job completion
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
  
      - name: Download built application artifact
        uses: actions/download-artifact@v4
        with:
          name: nestjs-app-${{ github.run_id }}
          path: ./
  
      - name: Start NestJS application in background
        env:
          NODE_ENV: production
          PORT: 3000
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Starting NestJS application..."
          yarn start &
          APP_PID=$!
          echo "Application started with PID $APP_PID. Waiting for it to be ready on port 3000..."
          
          # Robust wait for application to be ready
          timeout=90 # seconds
          interval=5  # seconds
          elapsed=0
          while ! nc -z localhost 3000; do
            if [ $elapsed -ge $timeout ]; then
              echo "Timeout: Application did not start on port 3000 within $timeout seconds."
              # Optionally, dump logs from the app if you have a way to capture them
              # kill $APP_PID
              exit 1
            fi
            echo "Port 3000 is not yet open. Retrying in $interval seconds..."
            sleep $interval
            elapsed=$((elapsed + interval))
  
            # Check if the background process is still alive
            if ! ps -p $APP_PID > /dev/null; then
              echo "Application process (PID $APP_PID) is no longer running. It might have crashed."
              # Optionally, try to find error logs
              exit 1
            fi
          done
          echo "Application is ready on port 3000."
  
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          # Ensure .zap_rules.tsv exists at the repo root or remove/comment out the next line
          rules_file_name: '.zap_rules.tsv'
          # Updated cmd_options to generate reports with names matching upload steps
          # -J for JSON report, -w for Markdown, -r for HTML, -x for XML
          cmd_options: >-
            -a
            -J zap_report.json
            -w zap_report.md
            -r zap_report.html
            -x zap_report.xml
          issue_title: 'ZAP Scan Found Vulnerabilities in [${{ github.repository }}]'
          fail_action: false # Set to true to fail the job if ZAP finds issues
          # Removed invalid inputs: report_html, report_md, report_xml
  
      - name: Upload ZAP Report (HTML)
        if: always() # Ensure report is uploaded even if ZAP scan fails action
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap_report.html # This file should now be generated by ZAP with this name
  
      - name: Upload ZAP Report (Markdown)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-md-report
          path: zap_report.md # This file should now be generated by ZAP with this name
      
      # Optional: Upload XML or JSON reports if needed
      # - name: Upload ZAP Report (XML)
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zap-xml-report
      #     path: zap_report.xml
      # - name: Upload ZAP Report (JSON)
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zap-json-report
      #     path: zap_report.json
