name: NestJS DevSecOps CI Pipeline

permissions:
  contents: read
  actions: read
  security-events: write
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'yarn' # Updated for Yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Updated for Yarn

      - name: Run ESLint
        run: yarn lint # Updated for Yarn

  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'yarn' # Updated for Yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Updated for Yarn

      - name: Run tests
        run: yarn test # Updated for Yarn

  sast:
    name: Static Analysis (Semgrep)
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST
        run: |
          semgrep scan \
            --config auto \
            --exclude "test/*" \
            --exclude "node_modules/*" \
            --exclude "dist/*" \
            --severity ERROR \
            --sarif \
            -o semgrep_report.sarif \
            || true

      - name: Upload Semgrep SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_report.sarif

      - name: Upload SARIF to GitHub Advanced Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep_report.sarif
          category: semgrep

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [sast]
    outputs:
      artifact_name: nestjs-app-${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'yarn' # Updated for Yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Updated for Yarn

      - name: Build NestJS application
        run: yarn build # Updated for Yarn

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nestjs-app-${{ github.run_id }}
          path: |
            dist
            node_modules
            package.json
            yarn.lock # Ensure yarn.lock is included if needed for runtime, though node_modules should suffice
            # Add other files needed to run the app

  dast:
    name: Dynamic Analysis (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          # No cache needed here if we are using the artifact from build job

      - name: Download built application artifact
        uses: actions/download-artifact@v4
        with:
          name: nestjs-app-${{ github.run_id }}
          path: ./

      # If your 'yarn start' script requires devDependencies or you didn't bundle node_modules in the artifact:
      # - name: Install production dependencies from artifact
      #   working-directory: ./ # Adjust if artifact unpacks into a subfolder
      #   run: yarn install --production --frozen-lockfile

      - name: Start NestJS application in background
        env:
          NODE_ENV: production
          PORT: 3000
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Starting NestJS application..."
          # Ensure your package.json's "start" script runs the production build, e.g., "node dist/main.js"
          # or "yarn workspace your-app-name start" if using yarn workspaces
          yarn start & # Updated for Yarn
          echo "Waiting for application to start..."
          sleep 30

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap_rules.tsv'
          cmd_options: '-a'
          issue_title: 'ZAP Scan Found Vulnerabilities in [${{ github.repository }}]'
          fail_action: false
          report_html: 'zap_report.html'
          report_md: 'zap_report.md'
          report_xml: 'zap_report.xml'

      - name: Upload ZAP Report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap_report.html

      - name: Upload ZAP Report (Markdown)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-md-report
          path: zap_report.md
